# -*- coding: utf-8 -*-
"""Homework3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wbCPuBW-uia9h52P9YgTZyA0PXxp6ONp
"""

import pandas as osPandas

dic = { "nomes": ["Pedro", "Jair", "Matheus"],
       "notas1": [8, 9, 10],
       "notas2": [10, 8, 7]
}

x = osPandas.DataFrame(dic)

print(x)
print("\n\n")

alunos = {"Pedro", "Paulo", "Junior"}
alunos2 = ["Pedro", "Paulo", "Jair"]
print(alunos)
print(alunos2)

